### PR TITLE
Dotnet2ndtry

### PR DESCRIPTION
**Pull request by danhalvorsen**
Purpose: Upgrade project for .net core 6.X. 

The PR MUST happen later than _Dotnet62ndtry #79_ (due to refs. to infra templates)

### CODE REVIEW

**Review by terjewoldseth — APPROVED** [review]

**Review by janid1967 — CHANGES_REQUESTED** [review]
Pipeline do not work yet

**Comment by janid1967** [comment]
> Pipeline do not work yet

image

**Comment by danhalvorsen** [comment]
Fails due to dependencies to a PR in infra -> https://github.com/equinor/procosys-infra/pull/79 (When the PR is approved and merge we will be in a better situation)

**Comment by danhalvorsen** [comment]
@janid1967 Grunnen til at pipelinen feilet  var at den annen PR ikke var merget inn på infra prosjektet.  Har kjørt pipelinen "grønn" flere ganger.  PR venter på din godkjenning (Eller må jeg lukke denne, og kjøre PR på ny) 

prosjektet.https://statoildeveloper.visualstudio.com/Statoil.NextGenProCoSys/_build/results?buildId=58864&view=results

**Review by janid1967 — APPROVED** [review]

**Pull request merged**
